"""Update schema for transport system

Revision ID: bec85b7efbe1
Revises: 87ebff5719af
Create Date: 2025-10-30 21:59:23.061364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bec85b7efbe1'
down_revision: Union[str, None] = '87ebff5719af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_types',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assignments',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('report_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('vehicle_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('driver_vehicle_logs')
    op.add_column('reports', sa.Column('requester_name', sa.String(length=255), nullable=False))
    op.add_column('reports', sa.Column('requester_phone', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('transport_type', mysql.CHAR(length=36), nullable=False))
    op.add_column('reports', sa.Column('use_stretcher', sa.Boolean(), nullable=False))
    op.add_column('reports', sa.Column('patient_name', sa.String(length=255), nullable=False))
    op.add_column('reports', sa.Column('patient_gender', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('patient_age', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('patient_history', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('pickup_address', sa.Text(), nullable=False))
    op.add_column('reports', sa.Column('destination_address', sa.Text(), nullable=False))
    op.add_column('reports', sa.Column('schedule_date', sa.Date(), nullable=False))
    op.add_column('reports', sa.Column('schedule_time', sa.Time(), nullable=False))
    op.add_column('reports', sa.Column('contact_person_name', sa.String(length=255), nullable=False))
    op.add_column('reports', sa.Column('contact_person_phone', sa.String(length=20), nullable=False))
    op.add_column('reports', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('attachment_ktp', sa.String(length=500), nullable=True))
    op.add_column('reports', sa.Column('attachment_house_photo', sa.String(length=500), nullable=True))
    op.add_column('reports', sa.Column('attachment_sharelok', sa.String(length=500), nullable=True))
    op.drop_constraint('reports_ibfk_3', 'reports', type_='foreignkey')
    op.drop_constraint('reports_ibfk_2', 'reports', type_='foreignkey')
    op.drop_constraint('reports_ibfk_1', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'vehicle_types', ['transport_type'], ['id'])
    op.drop_column('reports', 'reporter_id')
    op.drop_column('reports', 'location')
    op.drop_column('reports', 'driver_id')
    op.drop_column('reports', 'incident_type')
    op.drop_column('reports', 'requested_items')
    op.drop_column('reports', 'admin_id')
    op.add_column('vehicles', sa.Column('type', mysql.CHAR(length=36), nullable=False))
    op.add_column('vehicles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('vehicles', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'vehicles', 'vehicle_types', ['type'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'created_at')
    op.drop_column('vehicles', 'type')
    op.add_column('reports', sa.Column('admin_id', mysql.CHAR(length=36), nullable=True))
    op.add_column('reports', sa.Column('requested_items', mysql.TEXT(), nullable=True))
    op.add_column('reports', sa.Column('incident_type', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('reports', sa.Column('driver_id', mysql.CHAR(length=36), nullable=True))
    op.add_column('reports', sa.Column('location', mysql.TEXT(), nullable=False))
    op.add_column('reports', sa.Column('reporter_id', mysql.CHAR(length=36), nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_ibfk_1', 'reports', 'users', ['admin_id'], ['id'])
    op.create_foreign_key('reports_ibfk_2', 'reports', 'users', ['driver_id'], ['id'])
    op.create_foreign_key('reports_ibfk_3', 'reports', 'users', ['reporter_id'], ['id'])
    op.drop_column('reports', 'attachment_sharelok')
    op.drop_column('reports', 'attachment_house_photo')
    op.drop_column('reports', 'attachment_ktp')
    op.drop_column('reports', 'note')
    op.drop_column('reports', 'contact_person_phone')
    op.drop_column('reports', 'contact_person_name')
    op.drop_column('reports', 'schedule_time')
    op.drop_column('reports', 'schedule_date')
    op.drop_column('reports', 'destination_address')
    op.drop_column('reports', 'pickup_address')
    op.drop_column('reports', 'patient_history')
    op.drop_column('reports', 'patient_age')
    op.drop_column('reports', 'patient_gender')
    op.drop_column('reports', 'patient_name')
    op.drop_column('reports', 'use_stretcher')
    op.drop_column('reports', 'transport_type')
    op.drop_column('reports', 'requester_phone')
    op.drop_column('reports', 'requester_name')
    op.create_table('driver_vehicle_logs',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('driver_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('vehicle_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('report_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('start_location', mysql.TEXT(), nullable=True),
    sa.Column('end_location', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name='driver_vehicle_logs_ibfk_1'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name='driver_vehicle_logs_ibfk_2'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='driver_vehicle_logs_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('assignments')
    op.drop_table('vehicle_types')
    # ### end Alembic commands ###
